name: "Setup signal-cli"
description: "Setup Java and signal-cli"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: "21"
    - run: curl -L "https://github.com/AsamK/signal-cli/releases/download/v0.13.4/signal-cli-0.13.4.tar.gz" | tar -zx
      shell: bash
    - run: echo "signal-cli-0.13.4/bin" >> $GITHUB_PATH
      shell: bash
    - run: echo "RANDOM_SUFFIX=${RANDOM}${RANDOM}" >> $GITHUB_ENV
      shell: bash
    - uses: actions/cache@v3
      with:
        path: .signal-cli-data
        key: signal-cli-data-${{ env.RANDOM_SUFFIX }}
        restore-keys: |
          signal-cli-data-
        fail-on-cache-miss: true
