export const ACTIVITIES = [
  "badminton",
  "caving",
  "climbing",
  "coasteering",
  "kayaking",
  "members_night",
  "mountain_biking",
  "mountain_sports",
  "road_cycling",
  "social",
  "sup",
  "surfing",
  "tennis",
  "trips_overseas",
  "trips_uk",
  "walking",
  "windsurfing",
] as const;
