name: Backup

on:
  push:
    branches: [backup]

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-signal-cli
      - uses: actions/upload-artifact@v4
        with:
          name: signal-cli-data
          path: .signal-cli-data
          retention-days: 1
