name: Upload signal-cli data cache

on:
  push:
    #branches: [main] #uncoment to actually upload
    branches: [upload-cache]

jobs:
  upload-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: mkdir .signal-cli-data
      - run: unzip signal-cli-data.zip -d .signal-cli-data
      - run: echo "RANDOM_SUFFIX=${RANDOM}${RANDOM}" >> $GITHUB_ENV
      - uses: actions/cache/save@v4
        with:
          path: .signal-cli-data
          key: signal-cli-data-${{ env.RANDOM_SUFFIX }}
